### ISSUE TITLE
User can view current spending

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their current expenses

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the home page, the user will be able to scroll through their most recent spending. if there is no data yet, there will be instructions to start inputting expenses.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="259" alt="Screen Shot 2023-01-30 at 7 13 45 PM" src="https://user-images.githubusercontent.com/103090771/215654672-372e06a1-34e9-4c1b-a5dd-338bd8c888b4.png">
<img width="473" alt="Screen Shot 2023-01-30 at 7 21 08 PM" src="https://user-images.githubusercontent.com/103090771/215654759-ab6e1be0-30f3-4660-a8ee-a90be8245992.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] Create an index.html and styles.css file and build the header and footer of the app
- [x] When in desktop screen size, the footer links will move to the header
- [x] Add a 'current-spending-container' element to hold the current spending data
- [x] Create a scrollable text box that the user entries will be appended to. Label this 'Current Spending'.
- [x] if there is no data, add instructions for the user to follow
 
### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
