### ISSUE TITLE
User can view yearly spending snapshot

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their yearly spending in a bar graph

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the home page, the user will be able to view their yearly total spending, along with a bar graph. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="255" alt="Screen Shot 2023-01-30 at 7 26 39 PM" src="https://user-images.githubusercontent.com/103090771/215655508-4c15ccbb-b478-4669-8ee3-51c1c9b38b06.png">
<img width="473" alt="Screen Shot 2023-01-30 at 7 26 30 PM" src="https://user-images.githubusercontent.com/103090771/215655497-fb06cbe5-1fa5-4cf3-b878-a483a3adec4a.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] Create a container for the YTD snapshot with an appropriately labeled title and subtitle
- [x] NPM install recharts and make sure it is listed as a dependency in the package.json file
- [x] Create a bar-graph.jsx and design a bar chart using recharts website as a guide
- [x] Have the graph dynamically change in size with the YTD snapshot container

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
