### ISSUE TITLE
User can add an expense

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can add an expense item

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the "Add" tab, they will be able to add an expense by filling out a form. The user will then be redirected to the home page, where the expense will be displayed in the recent expenses.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="254" alt="Screen Shot 2023-01-30 at 7 29 00 PM" src="https://user-images.githubusercontent.com/103090771/215655798-21f0bf97-e403-4f99-86d6-e07d61b74f1a.png">
<img width="475" alt="Screen Shot 2023-01-30 at 7 29 17 PM" src="https://user-images.githubusercontent.com/103090771/215655806-1016ca9f-7c54-46cd-9fcd-03aebfcd037b.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] When the user clicks the add button, the <AddView/> should be rendered
- [x] Create a form that allows the user to enter all information needed about a transaction
- [x] Add a submit and cancel button
- [x] When the user submits the form, an entry needs to added into the finalProject database
- [x] The entry will then be appended to the Current spending textarea of the home page 
- [x] Entries must be listed in order of time and date and be appropriately labeled

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
