### ISSUE TITLE
User can edit an expense

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can edit an expense 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks the edit symbol on one of the the expenses on the home page, they will be able to edit that expense by making changes to a form

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="257" alt="Screen Shot 2023-01-30 at 7 31 53 PM" src="https://user-images.githubusercontent.com/103090771/215656141-ae8a088d-17eb-49b3-9701-afdc6bd7f220.png">
<img width="476" alt="Screen Shot 2023-01-30 at 7 31 44 PM" src="https://user-images.githubusercontent.com/103090771/215656153-0a534741-2d2f-4a0a-8622-8d0798981a79.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] Add an edit button onto each submission in the CurrentSpending component
- [x] onEditClick(), the user will be directed to the AddView
- [x] The 'Add Expense' button will show 'Edit Expense' using CSS class rules
- [x] The form will be prefilled with the FormData of the selected expense
- [x] The user will be directed to the Home page when 'Edit Expense' is clicked
- [x] The expense on the Current Spending will be changed to the corrected values

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server/index.js` to select the current entry to edit by entryId and fetch a PUT request to make changes to it
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
