### ISSUE TITLE
User can delete an expense

### ISSUE THREAD

**Issue by wang-morris** [wang-morris/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an expense

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user clicks the edit symbol on an expense from the home page, they will have the option to click a "delete" button to remove that expense. There will be a delete modal to confirm this action. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="256" alt="Screen Shot 2023-01-30 at 7 35 04 PM" src="https://user-images.githubusercontent.com/103090771/215656592-3e0625ca-c16f-470c-b594-95d27f04e632.png">
<img width="476" alt="Screen Shot 2023-01-30 at 7 35 15 PM" src="https://user-images.githubusercontent.com/103090771/215656602-ddf9fcee-279d-4208-9fe1-daaca8f3c866.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [x] create a modal component or add to EditExpense so that a modal pops up when the user clicks 'delete'. The modal should have a CANCEL and CONFIRM button
- [x] set up an app.delete method in the index.js file and ensure that it can delete an entry using HTTPie
- [x] create a method that will make a fetch request for the current entry to be deleted from the database
- [x] in App.jsx, the there will need to be a method to remove that entry from the front end
- [x] User is directed to the Home page after user deletes the entry

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
